import type { GhRepo } from "./types";

/**
 * Committed fallback snapshot of the real GitHub repos, captured from the
 * GitHub API. Used only when a live fetch fails (rate limit, network, or
 * GitHub downtime) so the site never renders empty or breaks the build.
 *
 * Auto-generated by scripts/refresh-snapshot.mjs — do not edit by hand.
 */
export const snapshotGeneratedAt = "2026-06-11";

export const repoSnapshot: GhRepo[] = [
  {
    name: "sylistly",
    full_name: "willywonka773202-cloud/sylistly",
    html_url: "https://github.com/willywonka773202-cloud/sylistly",
    description: null,
    language: "TypeScript",
    homepage: "https://sylistly.vercel.app",
    private: false,
    fork: false,
    archived: false,
    size: 377931,
    pushed_at: "2026-06-11T10:43:45Z",
  },
  {
    name: "bertos-body",
    full_name: "willywonka773202-cloud/bertos-body",
    html_url: "https://github.com/willywonka773202-cloud/bertos-body",
    description: null,
    language: "Python",
    homepage: null,
    private: false,
    fork: false,
    archived: false,
    size: 31741,
    pushed_at: "2026-06-10T00:05:38Z",
  },
  {
    name: "carpool-optimizer",
    full_name: "willywonka773202-cloud/carpool-optimizer",
    html_url: "https://github.com/willywonka773202-cloud/carpool-optimizer",
    description: null,
    language: "TypeScript",
    homepage: "https://carpool-optimizer-five.vercel.app",
    private: false,
    fork: false,
    archived: false,
    size: 449,
    pushed_at: "2026-06-06T13:36:29Z",
  },
  {
    name: "bertos-ai-os",
    full_name: "willywonka773202-cloud/bertos-ai-os",
    html_url: "https://github.com/willywonka773202-cloud/bertos-ai-os",
    description: null,
    language: "TypeScript",
    homepage: "https://bertos-ai-os.vercel.app",
    private: false,
    fork: false,
    archived: false,
    size: 4982,
    pushed_at: "2026-05-31T03:58:14Z",
  },
  {
    name: "deerfield-aquatics-schedule",
    full_name: "willywonka773202-cloud/deerfield-aquatics-schedule",
    html_url: "https://github.com/willywonka773202-cloud/deerfield-aquatics-schedule",
    description: null,
    language: "TypeScript",
    homepage: null,
    private: false,
    fork: false,
    archived: false,
    size: 627,
    pushed_at: "2026-05-27T20:41:43Z",
  },
  {
    name: "will-life-morning-dashboard",
    full_name: "willywonka773202-cloud/will-life-morning-dashboard",
    html_url: "https://github.com/willywonka773202-cloud/will-life-morning-dashboard",
    description: null,
    language: null,
    homepage: null,
    private: false,
    fork: false,
    archived: false,
    size: 0,
    pushed_at: "2026-05-25T13:39:44Z",
  },
  {
    name: "accounting",
    full_name: "willywonka773202-cloud/accounting",
    html_url: "https://github.com/willywonka773202-cloud/accounting",
    description: null,
    language: null,
    homepage: null,
    private: false,
    fork: false,
    archived: false,
    size: 0,
    pushed_at: "2026-05-22T13:16:48Z",
  },
];
